### ISSUE TITLE
Is it compatible with MaterializeCSS?

### ISSUE THREAD

**Issue by gusbemacbe** [marlenesco/material-cards#10]
Hello,

I want to use MaterializeCSS instead of Bootstrap, but I want to know if this template is compatible with it.

**Comment by marlenesco** [comment]
Yes, it is a stand-alone repository, you can use it with any front end framework or your own stylesheet, the only requirement is jQuery

**Comment by gusbemacbe** [comment]
Ciao Marlene,

I tested and it worked, but I had to change the grids and the classes for not entering conflict with Materialize because Bootstrap and Materialize use the same classes.

**Comment by marlenesco** [comment]
@gusbemacbe bootstrap grid is only an example, you can use with any grid system, front end framework or other stuff like Masonry library.

I hope you enjoy MC, 
cheers
