### ISSUE TITLE
Use cards in angular ..

### ISSUE THREAD

**Issue by Donia-AQ** [marlenesco/material-cards#14]
Hi, 
i used these cards in my angular application...

it works fine but there is a problem with the sizes of cards... i will attach a screenshot 
could you please help me where the problem could be.
thank you in advance 
![problem](https://user-images.githubusercontent.com/49990355/76913097-12b73a80-68c7-11ea-84f8-6e1877f3aff7.png)

**Comment by marlenesco** [comment]
Hi @Donia-AQ, probably the problem is in the card container size, show me the code, please

**Comment by marlenesco** [comment]
Try to put your card in a (proper) sized container, let me know, please
