### ISSUE TITLE
Issue in the image size

### ISSUE THREAD

**Issue by adelgebeely2020** [marlenesco/material-cards#15]
- When I hit the toggle button the image doesn’t shrink to be a small icon on the left top like in the demo.
- One more thing, when I compiled the less file, some lines in the css file stile underlined red as if something wrong in the copiled file. The overall, is the cards working well except for the image doesn’t get shrinked to be like an icon image in the top left corner of the card.
Below are two cards one before I hit the toggle button and the second one After. 
![image](https://user-images.githubusercontent.com/62954229/82959371-ce77a300-9fb7-11ea-8b26-b4e3964d711b.jpeg)

![image](https://user-images.githubusercontent.com/62954229/82959383-d8010b00-9fb7-11ea-9ecf-267cf24e495b.jpeg)

**Comment by marlenesco** [comment]
Hi @adelgebeely2020 show me your code, please.
I need more details, let me know
