### ISSUE TITLE
Flip button does not work on deployed site

### ISSUE THREAD

**Issue by deannapi** [marlenesco/material-cards#18]
I'm using React and I had to change the flip icons from `a` to `button` to avoid the `href `error``.
The flip buttons work on localhost but the cards to not flip on my deployed site. I also noticed that the `.click` on the `.material-card` has a strikethrough.

![image](https://user-images.githubusercontent.com/49648497/109848063-7b511180-7c15-11eb-8a89-2d548570bb46.png)

**Comment by marlenesco** [comment]
Hi @deannapi, 
sorry for the late reply, try to use the jQuery.on event handler.
But, in react you should not use jQuery and bind the event using the proper state.
Let me know, please
have a nice day
