### ISSUE TITLE
How can we make .mc-description full height on desktop, to accommodate arbitrary-length description text?

### ISSUE THREAD

**Issue by dimavolo** [marlenesco/material-cards#3]
Thank you for making a fantastic plugin. I am having trouble determining what CSS modifications I need in order to make .mc-description full height on large screens, to match the way it behaves on small screens.

Currently, if the description text is too long, it simply gets cut off. I have used overflow: scroll as a temporary solution, but what I'd really like is for the card to adjust its height to match any length of description text. I will couple that with a masonry layout.

Could you please help me determine what CSS changes I need to make in order to get the height of .mc-description to adjust dynamically to the text inside?

Thanks again!

**Comment by marlenesco** [comment]
Hi @attentiondmi, It's quite simple edit the less file `material-cards/less/material-cards.less`.

See the attachment below, it is what you need.

[material-cards.less.zip](https://github.com/marlenesco/material-cards/files/238440/material-cards.less.zip)

Have a nice day.

**Comment by dimavolo** [comment]
THANK YOU!

That was an unbelievably quick response time. I compiled and did a quick test: your fix works well!

Thanks again for being amazing.

**Comment by marlenesco** [comment]
For any question I'm here. ★ if you like...
