### ISSUE TITLE
Cards do not respond after element is dynamically added

### ISSUE THREAD

**Issue by AswaggyP** [marlenesco/material-cards#5]
I'm trying to use the cards to represent profiles that are dynamically loaded after the page is done loading. The cards work the first time (although they are out of place) but once I refresh the list, the cards appear correctly but do not respond to any interaction. After some debugging, I was able to confirm that the issue only occurs after I refresh the container. 

The cards work fine if they are statically placed on the page. Perhaps it has something to do with the refresh? In order to re-add elements, I clear all of them beforehand. I don't know if that could be it. 

Any tips or ideas would be appreciated. Thanks a bunch! 

Update: I was able to get them to work by calling on the cards to close after being added.

**Comment by marlenesco** [comment]
Hi @AswaggyP , can you send me a jsfiddle or a pen to try to fix (or a zip)?
Thank you

**Comment by AswaggyP** [comment]
Here's a mostly working pen. I couldn't get the close function to work but it demonstrates the freeze. 

http://codepen.io/aswaggyp/pen/EymzOL

**Comment by marlenesco** [comment]
Hi @AswaggyP look at this: http://codepen.io/marlenesco/pen/zBzqqk
Check at the end of yours `loadCards()` method.

If you create an element on the fly, you need to activate the correct behaviour.
Let me know if it's work.

Cheers

**Comment by marlenesco** [comment]
Hi @AswaggyP any news?

**Comment by AswaggyP** [comment]
Apologies! I've been busy the last few days. 

Yes! It works! I'm not super familiar with js so I hadn't realized that I should activate card behavior when they are added. 

Thanks for your quick response!
